/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\documents.glb -o ../src/Models/Documents.jsx 
Author: kyuukonneko (https://sketchfab.com/kyuukonneko)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/documents-e7ad0b118ffe4ff5bdaf0721d7ea0998
Title: Documents
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export function Model(props) {
  const { nodes, materials } = useGLTF("/documents.glb");

  const ref = useRef();
  useFrame((state) => {
    const t = state.clock.elapsedTime;
    ref.current.position.set(0, Math.sin(t * 0.5) / 4, 0);
    ref.current.rotation.set(
      Math.sin(t * 0.5) / 4,
      Math.sin(t * 0.5) / 10,
      Math.sin(t * 0.5) / 4
    );
  });

  return (
    <group {...props} dispose={null}>
      <group scale={0.06} ref={ref}>
        <group
          position={[-0.265, -6.136, 0.736]}
          rotation={[0, -0.096, -0.037]}
        >
          <mesh
            geometry={nodes.Paper006_paper_3_0.geometry}
            material={
              new THREE.MeshBasicMaterial({ map: materials.paper_3.map })
            }
            position={[0.129, 0.805, -0.007]}
            rotation={[Math.PI / 2, 0.022, 0]}
          />
          <mesh
            geometry={nodes.FileRing001_ring_0.geometry}
            material={new THREE.MeshBasicMaterial({ map: materials.ring.map })}
            position={[-5.872, -0.03, -4.09]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.287}
          />
          <mesh
            geometry={nodes.File001_cover_3_0.geometry}
            material={
              new THREE.MeshBasicMaterial({ map: materials.cover_3.map })
            }
            position={[0.05, 1.618, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
        <group
          position={[-1.22, 3.048, -0.55]}
          rotation={[3.132, 0.387, -3.085]}
        >
          <mesh
            geometry={nodes.File002_cover_2_0.geometry}
            material={
              new THREE.MeshBasicMaterial({ map: materials.cover_2.map })
            }
            position={[0.05, 1.618, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.FileRing002_ring_0.geometry}
            material={new THREE.MeshBasicMaterial({ map: materials.ring.map })}
            position={[-5.872, -0.03, -4.09]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.287}
          />
          <mesh
            geometry={nodes.Paper040_paper_2_0.geometry}
            material={
              new THREE.MeshBasicMaterial({ map: materials.paper_2.map })
            }
            position={[0.129, 0.805, -0.007]}
            rotation={[Math.PI / 2, 0.022, 0]}
          />
        </group>
        <group
          position={[-0.045, 5.962, 0.332]}
          rotation={[-0.014, 0.484, -0.044]}
        >
          <mesh
            geometry={nodes.File004_cover_0.geometry}
            material={new THREE.MeshBasicMaterial({ map: materials.cover.map })}
            position={[0.05, 1.618, 0]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            geometry={nodes.FileRing003_ring_0.geometry}
            material={new THREE.MeshBasicMaterial({ map: materials.ring.map })}
            position={[-5.872, -0.03, -4.09]}
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
            scale={0.287}
          />
          <mesh
            geometry={nodes.Paper045_paper_1_0.geometry}
            material={
              new THREE.MeshBasicMaterial({ map: materials.paper_1.map })
            }
            position={[0.129, 0.805, -0.007]}
            rotation={[Math.PI / 2, 0.022, 0]}
          />
        </group>
        <mesh
          geometry={nodes.Paper012_paper_4_0.geometry}
          material={new THREE.MeshBasicMaterial({ map: materials.paper_4.map })}
          position={[0.094, -4.484, 0.625]}
          rotation={[Math.PI / 2, -0.086, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/documents.glb");
